export const GLOBAL_CSV_DATA = `id,category,word1,word2,word3,word4,word5,word6,word7,word8
2501,Butterfly,Mariposa,Papillon,Schmetterling,Farfalla,Borboleta,Vlinder,1,Nature
2502,Bread,Pan,Pain,Brot,Pane,Chleb,Brood,1,Food
2503,Water,Agua,Eau,Wasser,Acqua,Voda,Mizu,1,Nature
2504,Friend,Amigo,Ami,Freund,Amico,Przyjaciel,Vriend,1,History
2505,House,Casa,Maison,Haus,Dom,Huis,1,History
2506,Sun,Sol,Soleil,Sonne,Sole,Słońce,Zon,1,Nature
2507,Moon,Luna,Lune,Mond,Luna,Księżyc,Maan,1,Nature
2508,Star,Estrella,Étoile,Stern,Stella,Gwiazda,Ster,1,Nature
2509,Book,Libro,Livre,Buch,Książka,Boek,1,History
2510,Cat,Gato,Chat,Katze,Kot,Kat,1,Nature
2511,Dog,Perro,Chien,Hund,Cane,Pies,Hond,1,Nature
2512,Flower,Flor,Fleur,Blume,Fiore,Kwiat,Bloem,1,Nature
2513,Tree,Árbol,Arbre,Baum,Albero,Drzewo,Boom,1,Nature
2514,Mountain,Montaña,Montagne,Berg,Montagna,Góra,Berg,1,Nature
2515,River,Río,Rivière,Fluss,Fiume,Rzeka,Rivier,1,Nature
2516,Sea,Mar,Mer,Meer,Mare,Morze,Zee,1,Nature
2517,Heart,Corazón,Cœur,Herz,Cuore,Serce,Hart,1,Science
2518,Apple,Manzana,Pomme,Apfel,Mela,Jabłko,Appel,1,Food
2519,Earth,Tierra,Terre,Erde,Terra,Ziemia,Aarde,1,Nature
2520,Fire,Fuego,Feu,Feuer,Fuoco,Ogień,Vuur,1,Nature
2521,Wind,Viento,Vent,Wind,Vento,Wiatr,Wind,1,Nature
2522,Bird,Pájaro,Oiseau,Vogel,Uccello,Ptak,Vogel,1,Nature
2523,Fish,Pez,Poisson,Fisch,Pesce,Ryba,Vis,1,Nature
2524,Head,Cabeza,Tête,Kopf,Testa,Głowa,Hoofd,1,Science
2525,Hand,Mano,Main,Hand,Mano,Ręka,Hand,1,Science
2526,Eye,Ojo,Œil,Auge,Occhio,Oko,Oog,1,Science
2527,Coffee,Café,Kaffee,Caffè,Kawa,Koffie,1,Food
2528,Milk,Leche,Lait,Milch,Latte,Mleko,Melk,1,Food
2529,Night,Noche,Nuit,Nacht,Notte,Noc,Nacht,1,Nature
2530,Day,Día,Jour,Tag,Giorno,Dzień,Dag,1,Nature
2531,Rain,Lluvia,Pluie,Regen,Pioggia,Deszcz,Regen,1,Nature
2532,Snow,Nieve,Neige,Schnee,Neve,Śnieg,Sneeuw,1,Nature
2533,City,Ciudad,Ville,Stadt,Città,Miasto,Stad,1,History
2534,School,Escuela,École,Schule,Scuola,Szkoła,School,1,History
2535,Teacher,Maestro,Professeur,Lehrer,Nauczyciel,Leraar,1,History
2536,Red,Rojo,Rouge,Rot,Rosso,Czerwony,Rood,1,Science
2537,Blue,Azul,Bleu,Blau,Blu,Niebieski,Blauw,1,Science
2538,Green,Verde,Vert,Grün,Zielony,Groen,1,Science
2539,Yellow,Amarillo,Jaune,Gelb,Giallo,Żółty,Geel,1,Science
2540,Black,Negro,Noir,Schwarz,Nero,Czarny,Zwart,1,Science
2541,White,Blanco,Blanc,Weiß,Bianco,Biały,Wit,1,Science
2542,Love,Amor,Amour,Liebe,Amore,Miłość,Liefde,1,Science
2543,Life,Vida,Vie,Leben,Vita,Życie,Leven,1,Science
2544,Time,Tiempo,Temps,Zeit,Tempo,Czas,Tijd,1,Science
2545,Music,Música,Musique,Musik,Musica,Muzyka,Muziek,1,Music
2546,Name,Nombre,Nom,Name,Nome,Imię,Naam,1,History
2547,Window,Ventana,Fenêtre,Fenster,Finestra,Okno,Raam,1,History
2548,Table,Mesa,Table,Tisch,Tavolo,Stół,Tafel,1,History
2549,Chair,Silla,Chaise,Stuhl,Sedia,Krzesło,Stoel,1,History
2550,Door,Puerta,Porte,Tür,Porta,Drzwi,Deur,1,History
2551,Boy,Niño,Garçon,Junge,Ragazzo,Chłopiec,Jongen,1,Science
2552,Girl,Niña,Fille,Mädchen,Ragazza,Dziewczynka,Meisje,1,Science
2553,Father,Padre,Père,Vater,Padre,Ojciec,Vader,1,History
2554,Mother,Madre,Mère,Mutter,Madre,Matka,Moeder,1,History
2555,Son,Hijo,Fils,Sohn,Figlio,Syn,Zoon,1,History
2556,Daughter,Hija,Fille,Tochter,Figlia,Córka,Dochter,1,History
2557,Brother,Hermano,Frère,Bruder,Fratello,Brat,Broer,1,History
2558,Sister,Hermana,Sœur,Schwester,Sorella,Siostra,Zus,1,History
2559,Grandfather,Abuelo,Grand-père,Großvater,Nonno,Dziadek,Grootvader,1,History
2560,Grandmother,Abuela,Grand-mère,Großmutter,Nonna,Babcia,Grootmoeder,1,History
2561,Uncle,Tío,Oncle,Onkel,Zio,Wujek,Oom,1,History
2562,Aunt,Tía,Tante,Tante,Zia,Ciocia,Tante,1,History
2563,Cousin,Primo,Cousin,Cousin,Cugino,Kuzyn,Neef,1,History
2564,Nephew,Sobrino,Neveu,Neffe,Nipote,Siostrzeniec,Neef,1,History
2565,Niece,Sobrina,Nièce,Nichte,Nipote,Siostrzenica,Nicht,1,History
2566,Baby,Bebé,Bébé,Baby,Neonato,Dziecko,Baby,1,Science
2567,Mouth,Boca,Bouche,Mund,Bocca,Usta,Mond,1,Science
2568,Nose,Nariz,Nez,Nase,Naso,Nos,Neus,1,Science
2569,Ear,Oreja,Oreille,Ohr,Orecchio,Ucho,Oor,1,Science
2570,Hair,Pelo,Cheveu,Haar,Capelli,Włosy,Haar,1,Science
2571,Face,Cara,Visage,Gesicht,Viso,Twarz,Gezicht,1,Science
2572,Shoulder,Hombro,Épaule,Schulter,Spalla,Ramię,Schouder,1,Science
2573,Arm,Brazo,Bras,Arm,Braccio,Ramię,Arm,1,Science
2574,Finger,Dedo,Doigt,Finger,Dito,Palec,Vinger,1,Science
2575,Leg,Pierna,Jambe,Bein,Gamba,Noga,Been,1,Science
2576,Foot,Pie,Pied,Fuß,Piede,Stopa,Voet,1,Science
2577,Back,Espalda,Dos,Rücken,Schiena,Plecy,Rug,1,Science
2578,Skin,Piel,Peau,Haut,Pelle,Skóra,Huid,1,Science
2579,Blood,Sangre,Sang,Blut,Sangue,Krew,Bloed,1,Science
2580,Bone,Hueso,Os,Knochen,Osso,Kość,Bot,1,Science
2581,Stomach,Estómago,Estomac,Magen,Stomaco,Żołądek,Maag,1,Science
2582,Brain,Cerebro,Cerveau,Gehirn,Cervello,Mózg,Brein,1,Science
2583,Bread,Pan,Pain,Brot,Pane,Chleb,Brood,1,Food
2584,Rice,Arroz,Riz,Reis,Riso,Ryż,Rijst,1,Food
2585,Meat,Carne,Viande,Fleisch,Carne,Mięso,Vlees,1,Food
2586,Chicken,Pollo,Poulet,Hähnchen,Pollo,Kurczak,Kip,1,Food
2587,Egg,Huevo,Œuf,Ei,Uovo,Jajko,Ei,1,Food
2588,Cheese,Queso,Fromage,Käse,Formaggio,Ser,Kaas,1,Food
2589,Butter,Mantequilla,Beurre,Butter,Burro,Masło,Boter,1,Food
2590,Fruit,Fruta,Fruit,Frucht,Frutta,Owoc,Vrucht,1,Food
2591,Banana,Plátano,Banane,Banane,Banana,Banan,Banaan,1,Food
2592,Orange,Naranja,Orange,Orange,Arancia,Pomarańcza,Sinaasappel,1,Food
2593,Potato,Patata,Pomme de terre,Kartoffel,Patata,Ziemniak,Aardappel,1,Food
2594,Tomato,Tomate,Tomate,Tomate,Pomodoro,Pomidor,Tomaat,1,Food
2595, Onion,Cebolla,Oignon,Zwiebel,Cipolla,Cebula,Ui,1,Food
2596,Garlic,Ajo,Ail,Knoblauch,Aglio,Czosnek,Knoflook,1,Food
2597,Salt,Sal,Sel,Salz,Sale,Sól,Zout,1,Food
2598,Sugar,Azúcar,Sucre,Zucker,Zucchero,Cukier,Suiker,1,Food
2599,Tea,Té,Thé,Tee,Tè,Herbata,Thee,1,Food
2600,Wine,Vino,Vin,Wein,Vino,Wino,Wijn,1,Food
2601,Beer,Cerveza,Bière,Bier,Birra,Piwo,Bier,1,Food
2602,Juice,Zumo,Jus,Saft,Succo,Sok,Sap,1,Food
2603,Plate,Plato,Assiette,Teller,Piatto,Talerz,Bord,1,Food
2604,Cup,Taza,Tasse,Tasse,Tazza,Filiżanka,Kop,1,Food
2605,Spoon,Cuchara,Cuillère,Löffel,Cucchiaio,Łyżka,Lepel,1,Food
2606,Knife,Cuchillo,Couteau,Messer,Coltello,Nóż,Mes,1,Food
2607,Fork,Tenedor,Fourchette,Gabel,Forchetta,Widelec,Vork,1,Food
2608,Shirt,Camisa,Chemise,Hemd,Camicia,Koszula,Overhemd,1,History
2609,Pants,Pantalones,Pantalon,Hose,Pantaloni,Spodnie,Broek,1,History
2610,Dress,Vestido,Robe,Kleid,Vestito,Sukienka,Jurk,1,History
2611,Skirt,Falda,Jupe,Rock,Gonna,Spódnica,Rok,1,History
2612,Coat,Abrigo,Manteau,Mantel,Cappotto,Płaszcz,Jas,1,History
2613,Hat,Sombrero,Chapeau,Hut,Cappello,Kapelusz,Hoed,1,History
2614,Shoe,Zapato,Chaussure,Schuh,Scarpa,But,Schoen,1,History
2615,Sock,Calcetín,Chaussette,Socke,Calza,Skarpetka,Sok,1,History
2616,Watch,Reloj,Montre,Uhr,Orologio,Zegarek,Horloge,1,History
2617,Bag,Bolsa,Sac,Tasche,Borsa,Torba,Tas,1,History
2618,Glasses,Gafas,Lunettes,Brille,Occhiali,Okulary,Bril,1,History
2619,Bed,Cama,Lit,Bett,Letto,Łóżko,Bed,1,History
2620,Sleep,Sueño,Sommeil,Schlaf,Sonno,Sen,Slaap,1,History
2621,Kitchen,Cocina,Cuisine,Küche,Cucina,Kuchnia,Keuken,1,History
2622,Bathroom,Baño,Salle de bain,Badzimmer,Bagno,Łazienka,Badkamer,1,History
2623,Garden,Jardín,Jardin,Garten,Giardino,Ogród,Tuin,1,History
2624,Floor,Suelo,Sol,Boden,Pavimento,Podłoga,Vloer,1,History
2625,Wall,Pared,Mur,Wand,Parete,Ściana,Muur,1,History
2626,Roof,Techo,Toit,Dach,Tetto,Dach,Dak,1,History
2627,Stairs,Escaleras,Escaliers,Treppe,Scale,Schody,Trap,1,History
2628,Key,Llave,Clé,Schlüssel,Chiave,Klucz,Sleutel,1,History
2629,Mirror,Espejo,Miroir,Spiegel,Specchio,Lustro,Spiegel,1,History
2630,Soap,Jabón,Savon,Seife,Sapone,Mydło,Zeep,1,History
2631,Towel,Toalla,Serviette,Handtuch,Asciugamano,Ręcznik,Handdoek,1,History
2632,Computer,Ordenador,Ordinateur,Computer,Computer,Komputer,Computer,1,Science
2633,Phone,Teléfono,Téléphone,Telefon,Telefono,Telefon,Telefoon,1,Science
2634,Camera,Cámara,Appareil,Kamera,Macchina,Aparat,Camera,1,Science
2635,Pen,Bolígrafo,Stylo,Stift,Penna,Długopis,Pen,1,History
2636,Paper,Papel,Papier,Papier,Carta,Papier,Papier,1,History
2637,Letter,Carta,Lettre,Brief,Lettera,List,Brief,1,History
2638,Street,Calle,Rue,Straße,Strada,Ulica,Straat,1,History
2639,Road,Camino,Chemin,Weg,Strada,Droga,Weg,1,History
2640,Bridge,Puente,Pont,Brücke,Ponte,Most,Brug,1,History
2641,Store,Tienda,Magasin,Laden,Negozio,Sklep,Winkel,1,History
2642,Park,Parque,Parc,Park,Parco,Park,Park,1,History
2643,Hospital,Hospital,Hôpital,Krankenhaus,Ospedale,Szpital,Ziekenhuis,3,Science
2644,Police,Policía,Police,Polizei,Polizia,Policja,Politie,1,Science
2645,Doctor,Médico,Médecin,Arzt,Dottore,Lekarz,Dokter,1,Science
2646,Student,Estudiante,Étudiant,Student,Studente,Student,Student,1,History
2647,Office,Oficina,Bureau,Büro,Ufficio,Biuro,Kantoor,1,History
2648,Work,Trabajo,Travail,Arbeit,Lavoro,Praca,Werk,1,History
2649,Money,Dinero,Argent,Geld,Denaro,Pieniądze,Geld,1,History
2650,Price,Precio,Prix,Preis,Prezzo,Cena,Prijs,1,History
2651,Bill,Factura,Facture,Rechnung,Conto,Rachunek,Rekening,1,History
2652,Ticket,Entrada,Billet,Karte,Biglietto,Bilet,Kaartje,1,History
2653,Map,Mapa,Carte,Karte,Mappa,Mapa,Kaart,1,Science
2654,Hotel,Hotel,Hôtel,Hotel,Hotel,Hotel,Hotel,1,History
2655,Beach,Playa,Plage,Strand,Spiaggia,Plaża,Strand,1,Nature
2656,Forest,Bosque,Forêt,Wald,Foresta,Las,Bos,1,Nature
2657,Desert,Desierto,Désert,Wüste,Deserto,Pustynia,Woestijn,3,Nature
2658,Lake,Lago,Lac,See,Lago,Jezioro,Meer,1,Nature
2659,Island,Isla,Île,Insel,Isola,Wyspa,Eiland,1,Nature
2660,Cloud,Nube,Nuage,Wolke,Nuvola,Chmura,Wolk,1,Nature
2661,Thunder,Trueno,Tonnerre,Donner,Tuono,Grzmot,Donder,3,Nature
2662,Storm,Tormenta,Tempête,Sturm,Tempesta,Burza,Storm,1,Nature
2663,Sky,Cielo,Ciel,Himmel,Cielo,Niebo,Hemel,1,Nature
2664,Bird,Pájaro,Oiseau,Vogel,Uccello,Ptak,Vogel,1,Nature
2665,Horse,Caballo,Cheval,Pferd,Cavallo,Koń,Paard,1,Nature
2666,Cow,Vaca,Vache,Kuh,Mucca,Krowa,Koe,1,Nature
2667,Pig,Cerdo,Cochon,Schwein,Maiale,Świnia,Varken,1,Nature
2668,Sheep,Oveja,Mouton,Schaf,Pecora,Owca,Schaap,1,Nature
2669,Goat,Cabra,Chèvre,Ziege,Capra,Koza,Geit,1,Nature
2670,Lion,León,Lion,Löwe,Leone,Lew,Leeuw,1,Nature
2671,Tiger,Tigre,Tigre,Tiger,Tigre,Tygrys,Tijger,1,Nature
2672,Bear,Oso,Ours,Bär,Orso,Niedźwiedź,Beer,1,Nature
2673,Elephant,Elefante,Éléphant,Elefant,Elefante,Słoń,Olifant,1,Nature
2674,Monkey,Mono,Singe,Affe,Scimmia,Małpa,Aap,1,Nature
2675,Rabbit,Conejo,Lapin,Hase,Coniglio,Królik,Konijn,1,Nature
2676,Snake,Serpiente,Serpent,Schlange,Serpente,Wąż,Slang,1,Nature
2677,Frog,Rana,Grenouille,Frosch,Rana,Żaba,Kikker,1,Nature
2678,Mouse,Ratón,Souris,Maus,Topo,Mysz,Muis,1,Nature
2679,Fly,Mosca,Mouche,Fliege,Mosca,Mucha,Vlieg,1,Nature
2680,Bee,Abeja,Abeille,Biene,Ape,Pszczoła,Bij,1,Nature
2681,Spider,Araña,Araignée,Spinne,Ragno,Pająk,Spin,1,Nature
2682,Ant,Hormiga,Fourmi,Ameise,Formica,Mrówka,Mier,1,Nature
2683,Worm,Gusano,Ver,Wurm,Verme,Robak,Worm,1,Nature
2684,Purple,Morado,Violet,Lila,Viola,Fioletowy,Paars,1,Science
2685,Pink,Rosa,Rose,Rosa,Rosa,Różowy,Roze,1,Science
2686,Orange,Naranja,Orange,Orange,Arancione,Pomarańczowy,Oranje,1,Science
2687,Brown,Marrón,Brun,Braun,Marrone,Brązowy,Bruin,1,Science
2688,Grey,Gris,Gris,Grau,Grigio,Szary,Grijs,1,Science
2689,Light,Luz,Lumière,Licht,Luce,Światło,Licht,1,History
2690,Heavy,Pesado,Lourd,Schwer,Pesante,Ciężki,Zwaar,1,History
2691,Big,Grande,Grand,Groß,Grande,Duży,Groot,1,History
2692,Small,Pequeño,Petit,Klein,Piccolo,Mały,Klein,1,History
2693,Fast,Rápido,Rapide,Schnell,Veloce,Szybki,Snel,1,History
2694,Slow,Lento,Lent,Langsam,Lento,Wolny,Langzaam,1,History
2695,Hot,Caliente,Chaud,Heiß,Caldo,Gorący,Heet,1,History
2696,Cold,Frío,Froid,Kalt,Freddo,Zimny,Koud,1,History
2697,New,Nuevo,Nouveau,Neu,Nuovo,Nowy,Nieuw,1,History
2698,Old,Viejo,Vieux,Alt,Vecchio,Stary,Oud,1,History
2699,Good,Bueno,Bon,Gut,Buono,Dobry,Goed,1,History
2700,Bad,Malo,Mauvais,Schlecht,Cattivo,Zły,Slecht,1,History
2701,Happy,Feliz,Heureux,Glücklich,Felice,Szczęśliwy,Gelukkig,1,History
2702,Sad,Triste,Triste,Traurig,Triste,Smutny,Triest,1,History
2703,Angry,Enfadado,Fâché,Böse,Arrabbiato,Zły,Boos,1,History
2704,Sick,Enfermo,Malade,Krank,Malato,Chory,Ziek,1,History
2705,Rich,Rico,Riche,Reich,Ricco,Bogaty,Rijk,1,History
2706,Poor,Pobre,Pauvre,Arm,Povero,Biedny,Arm,1,History
2707,Young,Joven,Jeune,Jung,Giovane,Młody,Jong,1,History
2708,Hard,Duro,Dur,Hart,Duro,Twardy,Hard,1,History
2709,Soft,Blando,Mou,Weich,Morbido,Miękki,Zacht,1,History
2710,Near,Cerca,Près,Nah,Vicino,Blisko,Dichtbij,1,History
2711,Far,Lejos,Loin,Fern,Lontano,Daleko,Ver,1,History
2712,Right,Derecha,Droite,Rechts,Destra,Prawo,Rechts,1,History
2713,Left,Izquierda,Gauche,Links,Sinistra,Lewo,Links,1,History
2714,True,Verdadero,Vrai,Wahr,Vero,Prawda,Waar,1,History
2715,False,Falso,Faux,Falsch,Falso,Fałsz,Vals,1,History
2716,Beautiful,Hermoso,Beau,Schön,Bello,Piękny,Mooi,1,History
2717,Ugly,Feo,Laid,Hässlich,Brutto,Brzydki,Lelijk,1,History
2718,Clean,Limpio,Propre,Sauber,Pulito,Czysty,Schoon,1,History
2719,Dirty,Sucio,Sale,Schmutzig,Sporco,Brudny,Vuil,1,History
2720,Full,Lleno,Plein,Voll,Pieno,Pełny,Vol,1,History
2721,Empty,Vacío,Vide,Leer,Vuoto,Pusty,Leeg,1,History
2722,Easy,Fácil,Facile,Einfach,Facile,Łatwy,Gemakkelijk,1,History
2723,Difficult,Difícil,Difficile,Schwer,Difficile,Trudny,Moeilijk,3,History
2724,Early,Temprano,Tôt,Früh,Presto,Wcześnie,Vroeg,1,History
2725,Late,Tarde,Tard,Spät,Tardi,Późno,Laat,1,History
2726,First,Primero,Premier,Erster,Primo,Pierwszy,Eerste,1,History
2727,Last,Último,Dernier,Letzter,Ultimo,Ostatni,Laatste,1,History
2728,More,Más,Plus,Mehr,Più,Więcej,Meer,1,History
2729,Less,Menos,Moins,Weniger,Meno,Mniej,Minder,1,History
2730,Open,Abierto,Ouvert,Offen,Aperto,Otwarty,Open,1,History
2731,Closed,Cerrado,Fermé,Geschlossen,Chiuso,Zamknięty,Gesloten,1,History
2732,Strong,Fuerte,Fort,Stark,Forte,Silny,Sterk,1,History
2733,Weak,Débil,Faible,Schwach,Debole,Słaby,Zwak,1,History
2734,Short,Corto,Court,Kurz,Corto,Krótki,Kort,1,History
2735,Long,Largo,Long,Lang,Lungo,Długi,Lang,1,History
2736,Wide,Ancho,Large,Breit,Largo,Szeroki,Breed,1,History
2737,Narrow,Estrecho,Étroit,Eng,Stretto,Wąski,Smal,1,History
2738,Dry,Seco,Sec,Trocken,Secco,Suchy,Droog,1,History
2739,Wet,Mojado,Mouillé,Nass,Bagnato,Mokry,Nat,1,History
2740,Cheap,Barato,Bon marché,Billig,Economico,Tani,Goedkoop,1,History
2741,Expensive,Caro,Cher,Teuer,Caro,Drogi,Duur,3,History
2742,Quiet,Silencioso,Calme,Ruhig,Silenzioso,Cichy,Stil,1,History
2743,Noisy,Ruidoso,Bruyant,Laut,Rumoroso,Głośny,Luidruchtig,1,History
2744,Safe,Seguro,Sûr,Sicher,Sicuro,Bezpieczny,Veilig,1,History
2745,Dangerous,Peligroso,Dangereux,Gefährlich,Pericoloso,Niebezpieczny,Gevaarlijk,3,History
2746,Sweet,Dulce,Sucré,Süß,Dolce,Słodki,Zoet,1,Food
2747,Sour,Agrio,Acide,Sauer,Acido,Kwaśny,Zuur,1,Food
2748,Bitter,Amargo,Amer,Bitter,Amaro,Gorzki,Bitter,1,Food
2749,Salty,Salado,Salé,Salzig,Salato,Słony,Zout,1,Food
2750,Kitchen,Cocina,Cuisine,Küche,Cucina,Kuchnia,Keuken,1,Food
2751,Fridge,Nevera,Frigo,Kühlschrank,Frigo,Lodówka,Koelkast,1,Food
2752,Oven,Horno,Four,Ofen,Forno,Piekarnik,Oven,1,Food
2753,Sink,Fregadero,Évier,Spülbecken,Lavandino,Zlew,Gootsteen,1,Food
2754,Shelf,Estante,Étagère,Regal,Scaffale,Półka,Plank,1,Food
2755,Drawer,Cajón,Tiroir,Schublade,Cassetto,Szuflada,Lade,1,Food
2756,Stove,Estufa,Poêle,Herd,Stufa,Piec,Fornuis,1,Food
2757,Pan,Sartén,Poêle,Pfanne,Padella,Patelnia,Pan,1,Food
2758,Pot,Olla,Marmite,Topf,Pentola,Garnek,Pan,1,Food
2759,Mug,Taza,Chope,Becher,Tazza,Kubek,Mok,1,Food
2760,Glass,Vaso,Verre,Glas,Bicchiere,Szklanka,Glas,1,Food
2761,Napkin,Servilleta,Serviette,Serviette,Tovagliolo,Serwetka,Servet,1,Food
2762,Bag,Bolsa,Sac,Tasche,Borsa,Torba,Tas,1,History
2763,Wallet,Cartera,Portefeuille,Brieftasche,Portafoglio,Portfel,Portemonnee,1,History
2764,Umbrella,Paraguas,Parapluie,Regenschirm,Ombrello,Parasol,Paraplu,1,History
2765,Tool,Herramienta,Outil,Werkzeug,Strumento,Narzędzie,Gereedschap,3,Science
2766,Hammer,Martillo,Marteau,Hammer,Martello,Młotek,Hamer,3,Science
2767,Nail,Clavo,Clou,Nagel,Chiodo,Gwóźdź,Nagel,3,Science
2768,Screw,Tornillo,Vis,Schraube,Vite,Śruba,Schroef,3,Science
2769,Wrench,Llave,Clé,Schlüssel,Chiave,Klucz,Sleutel,3,Science
2770,Saw,Sierra,Scie,Säge,Sega,Piła,Zaag,3,Science
2771,Paint,Pintura,Peinture,Farbe,Vernice,Farba,Verf,1,Science
2772,Glue,Pegamento,Colle,Kleber,Colla,Klej,Lijm,1,Science
2773,Tape,Cinta,Ruban,Band,Nastro,Taśma,Tape,1,Science
2774,Scissors,Tijeras,Ciseaux,Schere,Forbici,Nożyczki,Schaar,1,Science
2775,Ladder,Escalera,Échelle,Leiter,Scala,Drabina,Ladder,3,Science
2776,Wheel,Rueda,Roue,Rad,Ruota,Koło,Wiel,1,Cars
2777,Engine,Motor,Moteur,Motor,Motore,Silnik,Motor,3,Cars
2778,Tire,Neumático,Pneu,Reifen,Gomma,Opona,Band,1,Cars
2779,Brake,Freno,Frein,Bremse,Freno,Hamulec,Rem,1,Cars
2780,Gas,Gas,Gaz,Gas,Gas,Gaz,Gas,1,Cars
2781,Seat,Asiento,Siège,Sitz,Sedile,Siedzenie,Stoel,1,Cars
2782,Truck,Camión,Camion,LKW,Camion,Ciężarówka,Vrachtwagen,3,Cars
2783,Bus,Autobús,Bus,Bus,Autobus,Autobus,Bus,1,Cars
2784,Train,Tren,Train,Zug,Treno,Pociąg,Trein,1,Cars
2785,Plane,Avión,Avion,Flugzeug,Aereo,Samolot,Vliegtuig,3,Cars
2786,Boat,Barco,Bateau,Boot,Barca,Łódź,Boot,1,Cars
2787,Bicycle,Bicicleta,Vélo,Fahrrad,Bicicletta,Rower,Fiets,1,Cars
2788,Subway,Metro,Métro,U-Bahn,Metro,Metro,Metro,3,Cars
2789,Ticket,Billete,Billet,Ticket,Biglietto,Bilet,Ticket,1,History
2790,Passport,Pasaporte,Passeport,Reisepass,Passaporto,Paszport,Paspoort,3,History
2791,Suitcase,Maleta,Valise,Koffer,Valigia,Walizka,Koffer,1,History
2792,Map,Mapa,Carte,Carte,Mappa,Mapa,Kaart,1,History
2793,Language,Lengua,Langue,Sprache,Lingua,Język,Taal,3,History
2794,Word,Palabra,Mot,Wort,Parola,Słowo,Woord,1,History
2795,Sentence,Frase,Phrase,Satz,Frase,Zdanie,Zin,3,History
2796,Question,Pregunta,Question,Frage,Domanda,Pytanie,Vraag,1,History
2797,Answer,Respuesta,Réponse,Antwort,Risposta,Odpowiedź,Antwoord,1,History
2798,Story,Historia,Histoire,Geschichte,Storia,Opowieść,Verhaal,1,History
2799,Poem,Poema,Poème,Gedicht,Poesia,Wiersz,Gedicht,3,History
2800,Pen,Bolígrafo,Stylo,Kuli,Penna,Długopis,Pen,1,History
2801,Pencil,Lápiz,Crayon,Bleistift,Matita,Ołówek,Potlood,1,History
2802,Eraser,Goma,Gomme,Radiergummi,Gomma,Gumka,Gom,1,History
2803,Notebook,Cuaderno,Cahier,Notizbuch,Quaderno,Zeszyt,Notitieboek,1,History
2804,Library,Biblioteca,Bibliothèque,Bibliothek,Biblioteca,Biblioteka,Bibliotheek,1,History
2805,Page,Página,Page,Seite,Pagina,Strona,Pagina,1,History
2806,Zero,Cero,Zéro,Null,Zero,Zero,Nul,1,Science
2807,One,Uno,Un,Eins,Uno,Jeden,Een,1,Science
2808,Two,Dos,Deux,Zwei,Due,Dwa,Twee,1,Science
2809,Three,Tres,Trois,Drei,Tre,Trzy,Drie,1,Science
2810,Four,Cuatro,Quatre,Vier,Quattro,Cztery,Vier,1,Science
2811,Five,Cinco,Cinq,Fünf,Cinque,Pięć,Vijf,1,Science
2812,Six,Seis,Six,Sechs,Sei,Sześć,Zes,1,Science
2813,Seven,Siete,Sept,Sieben,Sette,Siedem,Zeven,1,Science
2814,Eight,Ocho,Huit,Acht,Otto,Osiem,Acht,1,Science
2815,Nine,Nueve,Neuf,Neun,Nove,Dziewięć,Negen,1,Science
2816,Ten,Diez,Dix,Zehn,Dieci,Dziesięć,Tien,1,Science
2817,Hundred,Cien,Cent,Hundert,Cento,Sto,Honderd,3,Science
2818,Thousand,Mil,Mille,Tausend,Mille,Tysiąc,Duizend,3,Science
`;
