
// Local data for high-reliability offline support and instant startup.
export const MASTER_CSV_DATA = `
ID,Category,CATDICT,WORD1,WORDDEF1,WORD2,WORDDEF2,WORD3,WORDDEF3,WORD4,WORDDEF4,SCORE,CAT21
101,GEMSTONES,"A precious or semi-precious stone used in jewelry.",DIAMOND,"A brilliant precious stone of pure carbon.",RUBY,"A red precious stone of the corundum family.",SAPPHIRE,"A blue precious stone of the corundum family.",EMERALD,"A green precious stone of the beryl family.",3,Science
102,CHESS PIECES,"A set of figures used in the game of chess.",KNIGHT,"A piece represented by a horse's head.",BISHOP,"A piece that moves diagonally any distance.",ROOK,"A piece that moves horizontally or vertically.",QUEEN,"The most powerful piece in chess.",1,Gaming
103,GAS GIANTS,"Large planets composed mostly of gases.",JUPITER,"The largest planet in our solar system.",SATURN,"The planet famous for its prominent ring system.",URANUS,"A cold giant planet with a tilted axis.",NEPTUNE,"The eighth and farthest planet from the Sun.",3,Astronomy
104,OFFICE SUPPLIES,"Common items used in an office setting.",STAPLER,"A device for binding papers with wire.",CLIP,"A small wire or plastic fastener for paper.",FOLDER,"A cover or case for holding loose papers.",MARKER,"A felt-tip pen used for writing or drawing.",1,Lifestyle
105,MYTHICAL CREATURES,"Creatures from folklore and mythology.",DRAGON,"A mythical fire-breathing lizard-like creature.",PHOENIX,"A bird that rises from its own ashes.",UNICORN,"A legendary horse with a single spiral horn.",GRIFFIN,"A creature with the body of a lion and wings of an eagle.",3,Mythology
106,PRIMARY COLORS,"The set of colors from which all others are mixed.",RED,"A color resembling blood or fire.",BLUE,"A color resembling the clear sky or sea.",YELLOW,"A color resembling ripe lemons or gold.",GREEN,"A color resembling grass or emeralds.",1,Art
107,GARDEN TOOLS,"Tools used for tending a garden.",SHOVEL,"A tool with a broad blade for digging.",RAKE,"A tool with a long handle and teeth for leveling soil.",HOE,"A tool used to loosen soil or remove weeds.",TROWEL,"A small handheld tool with a curved blade.",1,Lifestyle
108,PIANO PARTS,"Components of a piano instrument.",KEYS,"The levers pressed by fingers to play notes.",STRINGS,"Wire components that vibrate to create sound.",PEDALS,"Levers at the bottom pressed by feet.",HAMMERS,"Padded parts that strike the strings.",5,Music
109,ROMAN EMPERORS,"Leaders of the ancient Roman Empire.",AUGUSTUS,"The first Roman emperor and great-nephew of Caesar.",NERO,"An emperor known for his tyranny and eccentricity.",HADRIAN,"An emperor famous for building a great wall in Britain.",TRAJAN,"An emperor known for military expansion.",5,History
110,CITRUS FRUITS,"A group of fruits with acidic juices.",LEMON,"A yellow oval fruit with a sour taste.",LIME,"A small green fruit with a zesty flavor.",ORANGE,"A round orange fruit with sweet-tart juice.",GRAPEFRUIT,"A large citrus fruit with a bitter-sweet taste.",1,Food
111,NOBLE GASES,"Elements that are very stable and unreactive.",HELIUM,"The second lightest and second most abundant element.",NEON,"A gas used in brightly glowing advertising signs.",ARGON,"The third most abundant gas in Earth's atmosphere.",XENON,"A heavy gas used in some specialized lamps.",5,Science
112,WOODWIND INSTRUMENTS,"Musical instruments played by blowing air through them.",FLUTE,"A slender pipe played by blowing across a hole.",CLARINET,"A cylindrical pipe with a single-reed mouthpiece.",OBOE,"A slender pipe with a double-reed mouthpiece.",BASSOON,"A large woodwind instrument with a double reed.",3,Music
113,GREEK GODS,"Powerful deities from ancient Greek religion.",ZEUS,"The king of the gods and god of the sky.",HERA,"The queen of the gods and goddess of marriage.",POSEIDON,"The god of the sea and earthquakes.",HADES,"The god of the underworld and the dead.",3,Mythology
114,AFRICAN ANIMALS,"Diverse wildlife found on the African continent.",LION,"A large social cat known as the king of beasts.",ELEPHANT,"The largest land animal with a long trunk.",GIRAFFE,"The tallest land animal with a very long neck.",ZEBRA,"A wild horse-like animal with black and white stripes.",1,Animals
115,TYPES OF CLOUDS,"Visible masses of water droplets in the sky.",CUMULUS,"Puffy white clouds that look like cotton wool.",STRATUS,"Flat grey clouds that often cover the whole sky.",CIRRUS,"Thin wispy clouds that form at high altitudes.",NIMBUS,"Dark heavy clouds that typically bring rain.",3,Nature
116,DINOSAURS,"Extinct reptiles that ruled the Earth long ago.",STEGOSAURUS,"A herbivore with large bony plates on its back.",TRICERATOPS,"A dinosaur with three horns on its face.",VELOCIRAPTOR,"A small but fast and deadly feathered predator.",BRACHIOSAURUS,"A massive dinosaur with a very long neck.",3,History
117,CARD GAMES,"Games played with a deck of playing cards.",POKER,"A game involving betting and strategic hand values.",BRIDGE,"A trick-taking game played by four players in pairs.",SOLITAIRE,"A game usually played by a single person.",RUMMY,"A game based on matching cards of the same rank.",1,Gaming
118,PARTS OF A CELL,"Basic structural components of living organisms.",NUCLEUS,"The control center containing genetic material.",RIBOSOME,"Small structures that make proteins for the cell.",MITOCHONDRIA,"The power plant that produces energy for the cell.",MEMBRANE,"The thin outer layer that protects the cell.",5,Science
119,EUROPEAN CAPITALS,"Principal cities of nations within Europe.",PARIS,"The capital city of France known for the Eiffel Tower.",LONDON,"The capital city of the United Kingdom.",BERLIN,"The capital city of Germany with a rich history.",ROME,"The capital city of Italy known for the Colosseum.",1,Geography
120,TYPES OF PASTA,"Dough-based food shapes from Italian cuisine.",SPAGHETTI,"Long thin cylindrical strands of pasta.",PENNE,"Short tube-shaped pasta with angled ends.",FUSILLI,"Pasta shaped like small corkscrews or spirals.",LASAGNA,"Wide flat sheets of pasta used in layered dishes.",1,Food
121,DESERT PLANTS,"Flora adapted to extremely dry environments.",CACTUS,"Plants with spines that store water in their stems.",SUCCULENT,"Plants with thick fleshy parts for water storage.",SAGEBRUSH,"A shrubby plant common in North American deserts.",ACACIA,"A tree or shrub often found in arid regions.",3,Nature
122,ASTRONOMICAL BODIES,"Objects naturally occurring in outer space.",PLANET,"A large celestial body orbiting a star.",MOON,"A natural satellite that orbits a planet.",COMET,"A small icy body that releases gas and dust.",ASTEROID,"A small rocky body orbiting the Sun.",1,Astronomy
123,SHAKESPEARE PLAYS,"Famous theatrical works by the Bard of Avon.",HAMLET,"A tragedy about a prince seeking revenge for his father.",MACBETH,"A dark play about ambition and royal murder.",OTHELLO,"A tragedy dealing with jealousy and betrayal.",TEMPEST,"A play involving magic and a remote island.",5,Literature
124,COMPUTER HARDWARE,"Physical components of a computing system.",PROCESSOR,"The central brain that executes instructions.",MONITOR,"The screen used to display visual output.",KEYBOARD,"The primary device used for typing input.",MOTHERBOARD,"The main circuit board that connects everything.",3,Technology
125,HERBS AND SPICES,"Plants used for flavoring and seasoning food.",BASIL,"A green leaf used commonly in Italian pesto.",CINNAMON,"A sweet spice derived from the bark of trees.",TURMERIC,"A yellow spice known for health benefits.",OREGANO,"A herb used frequently in pizza and pasta sauce.",1,Food
126,POLITICAL SYSTEMS,"Methods by which a state is governed.",DEMOCRACY,"A system where citizens hold the governing power.",MONARCHY,"A system ruled by a king or queen.",REPUBLIC,"A state where power is held by elected officials.",OLIGARCHY,"A system where a small group holds all power.",5,Politics
127,OCEAN ZONES,"Different layers of the Earth's oceans.",SUNLIGHT,"The top layer where most marine life resides.",TWILIGHT,"A deeper layer with very little light penetration.",MIDNIGHT,"A dark layer where no sunlight reaches.",ABYSSAL,"The extremely deep and cold part of the ocean.",5,Science
128,TYPES OF FOOTWEAR,"Items worn on the feet for protection or fashion.",SNEAKER,"Casual athletic shoes with rubber soles.",BOOT,"Footwear that covers the foot and the ankle.",SANDAL,"Open footwear consisting of a sole and straps.",SLIPPER,"Light soft shoe worn indoors for comfort.",1,Lifestyle
129,NORSE DEITIES,"Gods and goddesses from Scandinavian mythology.",ODIN,"The Allfather and god of wisdom and war.",THOR,"The god of thunder who wields the hammer Mjolnir.",LOKI,"The shape-shifting trickster god of Norse myth.",FREYA,"The goddess of love beauty and fertility.",3,Mythology
130,ELEMENTARY PARTICLES,"Fundamental building blocks of the universe.",ELECTRON,"A stable subatomic particle with a negative charge.",QUARK,"A basic constituent of matter like protons.",PHOTON,"A particle representing a quantum of light.",NEUTRINO,"A subatomic particle with very little mass.",5,Science
131,FAMOUS ARCHITECTS,"Designers of iconic buildings and structures.",WRIGHT,"Famous for the Fallingwater house and organic style.",GAUDI,"Known for the unique Sagrada Familia in Barcelona.",HADID,"A modern architect known for futuristic designs.",EIFFEL,"The engineer who designed the famous Paris tower.",5,Art
132,SOUTH AMERICAN COUNTRIES,"Nations located in the southern part of the Americas.",BRAZIL,"The largest country in South America by area.",ARGENTINA,"Known for its vast plains and the city of Buenos Aires.",CHILE,"A long narrow country along the Pacific coast.",PERU,"Home to the ancient Inca site of Machu Picchu.",1,Geography
133,COFFEE TYPES,"Different ways of preparing coffee beverages.",ESPRESSO,"A concentrated coffee brewed under high pressure.",LATTE,"A coffee drink made with espresso and steamed milk.",CAPPUCCINO,"Espresso topped with foamed milk and steam.",MOCHA,"A chocolate-flavored variant of a caffe latte.",1,Food
134,WINTER SPORTS,"Athletic activities typically performed on snow or ice.",SKIING,"Sliding down snow-covered slopes on long boards.",HOCKEY,"A fast-paced team game played on ice with sticks.",CURLING,"A game where heavy stones are slid across ice.",LUGE,"Racing down an ice track on a small sled.",3,Sports
135,FURNITURE PIECES,"Functional objects used in human habitations.",CHAIR,"A piece of furniture for one person to sit on.",TABLE,"A flat surface supported by legs used for working.",SOFA,"A long upholstered seat for more than one person.",CABINET,"A piece of furniture with shelves or drawers.",1,Lifestyle
136,CRYPTID CREATURES,"Creatures whose existence is claimed but unproven.",BIGFOOT,"A large hairy ape-like creature of North America.",NESSIE,"The legendary monster of Loch Ness in Scotland.",YETI,"The abominable snowman of the Himalayan mountains.",CHUPACABRA,"A legendary creature said to attack livestock.",3,Mythology
137,PARTS OF A SHIP,"Structural elements of a nautical vessel.",HULL,"The main body of a ship or boat.",MAST,"A tall upright post that carries the sails.",ANCHOR,"A heavy device used to hold a ship in place.",STERN,"The rear or aft-most part of a ship.",5,Lifestyle
138,GEOLOGICAL ERAS,"Major divisions of geological time.",PALEOZOIC,"The era of ancient life like fish and ferns.",MESOZOIC,"The era of middle life known for dinosaurs.",CENOZOIC,"The current era known as the age of mammals.",PRECAMBRIAN,"The earliest span of Earth's history.",5,History
139,TYPES OF DANCE,"Different styles of rhythmic human movement.",BALLET,"A highly technical and artistic form of dance.",SALSA,"A lively social dance from Latin America.",HIPHOP,"A street dance style associated with rap culture.",FLAMENCO,"A passionate traditional dance from Spain.",3,Art
140,CONSTELLATIONS,"Groups of stars forming recognizable patterns.",ORION,"The hunter constellation with a distinct belt.",SCORPIUS,"A constellation that resembles a scorpion.",CASSIOPEIA,"A W-shaped constellation in the northern sky.",PEGASUS,"The winged horse constellation from Greek myth.",3,Astronomy
141,DESSERT CATEGORIES,"Broad types of sweet food courses.",CAKE,"A sweet baked bread-like food often frosted.",PIE,"A baked dish with a pastry crust and filling.",PUDDING,"A soft creamy dessert often milk-based.",PASTRY,"Baked dough products like tarts and danishes.",1,Food
142,FAMOUS EXPLORERS,"People who traveled to discover new lands.",COLUMBUS,"The navigator who reached the Americas in 1492.",MAGELLAN,"Lead the first expedition to sail around the world.",MARCO POLO,"Traveled from Venice to China in the 13th century.",COOK,"Famous for his voyages to the Pacific islands.",3,History
143,COMPUTER PROGRAMMING LANGUAGES,"Codes used to write software instructions.",PYTHON,"A popular language known for its readability.",JAVA,"A widely used language for enterprise software.",SWIFT,"A language developed by Apple for iOS apps.",COBOL,"An older language used mainly in business systems.",5,Technology
144,INSECT TYPES,"Small animals with six legs and three body parts.",BEETLE,"An insect with hard front wings that form covers.",BUTTERFLY,"Known for its large colorful wings and migration.",BEE,"A stinging insect that produces honey and wax.",ANT,"A social insect known for working in colonies.",1,Animals
145,SCIENTIFIC INSTRUMENTS,"Tools used by scientists for measurement and observation.",MICROSCOPE,"Used for viewing objects that are too small to see.",BAROMETER,"An instrument used to measure atmospheric pressure.",SEISMOGRAPH,"A device that records the vibrations of earthquakes.",SCALPEL,"A small sharp knife used in surgery or dissection.",3,Science
146,LITERARY GENRES,"Categories of artistic or written works.",MYSTERY,"Fiction involving a crime or secret to be solved.",HORROR,"Writing intended to scare or disgust the reader.",MEMOIR,"A factual account of a person's specific life experiences.",SATIRE,"Using humor or irony to criticize people or society.",3,Literature
147,PARTS OF AN AUTOMOBILE,"Key components of a motor vehicle.",ENGINE,"The machine that converts fuel into motion.",BRAKE,"A device used for slowing or stopping the car.",CLUTCH,"A mechanism that engages and disengages gears.",RADIATOR,"A cooling device that prevents the engine from overheating.",3,Cars
148,TYPES OF PAINTING,"Different techniques and media used in art.",WATERCOLOR,"Paint made with pigments dissolved in water.",FRESCO,"Painting done on fresh wet plaster or walls.",OIL,"Paint using pigments mixed with drying oils.",ACRYLIC,"A fast-drying paint made of pigment in resin.",3,Art
149,FAMOUS COMPOSERS,"Creators of significant musical works.",BEETHOVEN,"A German composer who became deaf late in life.",MOZART,"A prolific child prodigy of the Classical era.",BACH,"A master of baroque music and the organ.",TCHAIKOVSKY,"The Russian composer of the Nutcracker ballet.",3,Music
150,REPTILES,"Cold-blooded vertebrates with scaly skin.",TURTLE,"A reptile with a hard bony shell on its back.",CROCODILE,"A large predatory reptile found in wetlands.",LIZARD,"A reptile with a long body and a tail.",COBRA,"A venomous snake known for its hood.",1,Animals
151,ANCIENT EGYPTIAN TERMS,"Words related to the history of ancient Egypt.",PHARAOH,"The title given to the ancient Egyptian kings.",HIEROGLYPH,"A picture-based writing system used in Egypt.",PYRAMID,"A monumental structure with a square base.",PAPYRUS,"A material made from reeds used for writing.",3,History
152,TYPES OF TREES,"Different categories of woody perennial plants.",OAK,"A sturdy tree known for its acorns and hardwood.",PINE,"An evergreen tree with needles and cones.",MAPLE,"Famous for its winged seeds and sugary sap.",WILLOW,"A tree with long flexible branches and narrow leaves.",1,Nature
153,WEATHER INSTRUMENTS,"Devices used to monitor the atmosphere.",ANEMOMETER,"An instrument used for measuring wind speed.",HYGROMETER,"A tool used to measure the humidity in the air.",THERMOMETER,"A common device for measuring temperature.",RADAR,"Used to detect rain and track storm systems.",3,Science
154,BASKETBALL TERMS,"Vocabulary used in the game of basketball.",DRIBBLING,"Bouncing the ball repeatedly while moving.",REBOUND,"Catching the ball after a missed shot attempt.",ASSIST,"A pass that directly leads to a made basket.",SLAM DUNK,"A powerful shot where the ball is slammed in.",1,Sports
155,TYPES OF FRUIT,"Broad categories of edible plant parts.",BERRY,"A small pulpy and often edible fruit.",MELON,"A large fleshy fruit with many seeds like watermelon.",STONE FRUIT,"Fruits with a single large pit like a peach.",LEGUME,"Fruits that grow in pods like peas or beans.",1,Food
156,EGYPTIAN DEITIES,"Gods and goddesses of ancient Egypt.",OSIRIS,"The god of the afterlife and the dead.",ISIS,"The goddess of magic motherhood and healing.",ANUBIS,"The god of mummification with a jackal head.",RA,"The ancient sun god who traveled the sky.",3,Mythology
157,MEASUREMENT UNITS,"Standard quantities used to express size or weight.",KILOGRAM,"The metric unit used for measuring mass.",LITER,"A metric unit used for measuring volume.",METER,"The fundamental metric unit of length.",WATT,"A unit of power representing energy per second.",1,Science
158,LITERARY DEVICES,"Techniques used by writers to enhance meaning.",METAPHOR,"A comparison not using like or as.",SIMILE,"A comparison using words like like or as.",ALLITERATION,"The repetition of the same starting sounds.",IRONY,"When the outcome is the opposite of expectation.",5,Literature
159,MUSICAL TEMPO TERMS,"Italian words describing the speed of music.",ALLEGRO,"A musical term meaning quick and lively.",ADAGIO,"A term indicating a slow and stately pace.",PRESTO,"A direction to play music very fast.",LENTO,"A musical direction to play slowly.",5,Music
160,FAMOUS SCIENTISTS,"Individuals who made major discoveries.",NEWTON,"Formulated the laws of motion and gravity.",EINSTEIN,"Developed the theory of general relativity.",CURIE,"A pioneer in radioactivity and Nobel winner.",DARWIN,"Proposed the theory of evolution by natural selection.",3,Science
161,CURRENCY NAMES,"Names of money used in various countries.",DOLLAR,"The primary currency of the United States.",EURO,"The common currency used in much of Europe.",YEN,"The official currency used in Japan.",POUND,"The currency used in the United Kingdom.",1,Economics
162,TYPES OF ARCHES,"Architectural structures used in building.",POINTED,"A sharp arch common in Gothic architecture.",ROUND,"A semi-circular arch typical of Roman style.",HORSESHOE,"An arch that curves more than a semicircle.",FLAT,"An arch with little or no vertical curve.",5,Art
163,MOUNTAIN RANGES,"Series of mountains connected by high ground.",HIMALAYAS,"The highest mountain range in Asia.",ANDES,"The longest continental mountain range in the world.",ALPS,"A major mountain range located in Europe.",ROCKIES,"A large mountain range in western North America.",1,Geography
164,PHARMACEUTICAL TERMS,"Words related to medicine and drugs.",VACCINE,"A substance used to provide immunity to diseases.",ANTIBIOTIC,"A drug used to treat bacterial infections.",DOSAGE,"The specific amount of medicine to be taken.",GENERIC,"A drug that is not sold under a brand name.",3,Science
165,CHESS TACTICS,"Strategic maneuvers in the game of chess.",FORK,"When one piece attacks two or more enemy pieces.",PIN,"Attacking a piece that cannot move without loss.",SKEWER,"An attack along a line that forces a piece to move.",GAMBIT,"Sacrificing a piece to gain a strategic advantage.",5,Gaming
166,TYPES OF BRIDGES,"Different engineering designs for crossing gaps.",SUSPENSION,"A bridge hung from cables like the Golden Gate.",ARCH,"A bridge supported by curved structures.",CANTILEVER,"A bridge with structures projecting horizontally.",TRUSS,"A bridge made of connected triangular elements.",5,Art
167,FAMOUS PAINTERS,"Artists known for their exceptional works.",PICASSO,"A pioneer of the Cubist art movement.",MONET,"A key figure in the Impressionist movement.",REMBRANDT,"A Dutch master of light and shadow.",VAN GOGH,"The post-impressionist who painted Starry Night.",3,Art
168,AEROSPACE TERMS,"Vocabulary related to flight and space travel.",LIFT,"The upward force that allows planes to fly.",THRUST,"The forward force that drives an aircraft.",DRAG,"The resistance force that slows an aircraft.",ORBIT,"The path of a celestial body around another.",3,Technology
169,PARTS OF A FLOWER,"Reproductive components of flowering plants.",PETAL,"The colorful part that attracts pollinators.",STAMEN,"The male part that produces pollen grains.",PISTIL,"The female part that produces the seeds.",SEPAL,"The small leaf-like parts that protect the bud.",5,Science
170,TYPES OF CLOTHING FABRIC,"Materials used for making garments.",COTTON,"A soft fiber harvested from plants.",SILK,"A fine strong fiber produced by silkworms.",WOOL,"The thick hair of sheep used for warm clothes.",DENIM,"A sturdy cotton twill fabric used for jeans.",1,Lifestyle
171,CONSTITUTIONAL AMENDMENTS,"Changes or additions to the US Constitution.",SUFFRAGE,"Relating to the right to vote for citizens.",PROHIBITION,"The period when alcohol was banned in the US.",FREEDOM,"Relating to speech religion and assembly.",DUE PROCESS,"Fair treatment through the judicial system.",5,Politics
172,RIVERS OF THE WORLD,"Major natural streams of flowing water.",AMAZON,"The largest river by discharge volume in Brazil.",NILE,"The longest river in the world flowing through Africa.",GANGES,"A sacred river in India and Bangladesh.",DANUBE,"The second longest river in Europe.",1,Geography
173,TYPES OF POETRY,"Different structures and styles of verse.",SONNET,"A fourteen-line poem with a specific rhyme scheme.",HAIKU,"A three-line Japanese poem about nature.",LIMERICK,"A humorous five-line poem with an AABBA rhyme.",EPIC,"A long narrative poem about heroic deeds.",3,Literature
174,FAMOUS INVENTORS,"People who created ground-breaking technology.",EDISON,"Inventor of the light bulb and phonograph.",TESLA,"Known for developing alternating current power.",BELL,"The inventor of the first practical telephone.",WRIGHT,"Brothers who achieved the first powered flight.",3,History
175,TYPES OF CHEESE,"Different varieties of dairy products.",CHEDDAR,"A popular firm English cow's milk cheese.",MOZZARELLA,"A soft white Italian cheese often on pizza.",GORGONZOLA,"A crumbly Italian blue cheese with veins.",PARMESAN,"A hard granular aged Italian cheese.",1,Food
176,PARTS OF THE EYE,"Biological components used for vision.",CORNEA,"The clear front part of the eye covering the iris.",RETINA,"The layer at the back that senses light.",PUPIL,"The dark circular opening in the center.",LENS,"The structure that focuses light onto the back.",5,Science
177,CRIMINAL LAW TERMS,"Vocabulary used in legal systems.",FELONY,"A serious crime punishable by prison time.",VERDICT,"The final decision reached by a jury.",WARRANT,"A legal document authorizing an arrest or search.",PAROLE,"The early release of a prisoner before their term.",3,Politics
178,TYPES OF VOLCANOES,"Different shapes and eruption styles.",SHIELD,"A broad flat volcano with gentle slopes.",STRATO,"A tall cone-shaped volcano with violent eruptions.",CALDERA,"A large crater formed after a massive eruption.",CINDER,"A small simple cone built around a vent.",5,Nature
179,BAKING INGREDIENTS,"Common substances used in baked goods.",YEAST,"A fungus used as a leavening agent for bread.",FLOUR,"Powder made from grinding grains or nuts.",SUGAR,"A sweet crystalline substance from cane or beets.",BUTTER,"A dairy product made from churned cream.",1,Food
180,FAMOUS LANDMARKS,"Well-known natural or man-made structures.",COLOSSEUM,"The massive ancient amphitheater in Rome.",LOUVRE,"The world's largest art museum in Paris.",PETRA,"An ancient city carved into red rocks in Jordan.",STONEHENGE,"The prehistoric circle of stones in England.",3,Geography
181,COMPUTER NETWORKING TERMS,"Vocabulary related to connecting computers.",ROUTER,"A device that directs data across a network.",FIREWALL,"A security system that controls network traffic.",ETHERNET,"A common technology for local area networks.",PROTOCOL,"A set of rules for data communication.",5,Technology
182,TYPES OF ROCKS,"Broad categories of geological materials.",SEDIMENTARY,"Rocks formed from layers of accumulated sand.",IGNEOUS,"Rocks formed from the cooling of molten lava.",METAMORPHIC,"Rocks changed by intense heat and pressure.",GRANITE,"A common type of hard igneous rock.",3,Nature
183,FAMOUS AUTHORS,"Writers known for influential books.",DICKENS,"Wrote classic tales of Victorian London.",TWAIN,"The American author of Tom Sawyer.",AUSTEN,"Known for novels about the British gentry.",ORWELL,"The author of Nineteen Eighty-Four.",3,Literature
184,HOCKEY TERMS,"Vocabulary from the sport of ice hockey.",PUCK,"The hard rubber disk used in the game.",POWER PLAY,"When one team has a numerical advantage.",CREASE,"The area in front of the goal where the goalie stays.",ICING,"Sending the puck across the entire rink.",1,Sports
185,ANCIENT GREEK CITIES,"Major city-states of the Greek world.",ATHENS,"Known for democracy and the Parthenon.",SPARTA,"Famous for its disciplined military society.",CORINTH,"A major trade center on the Greek isthmus.",DELPHI,"Home to the famous oracle of Apollo.",3,History
186,TYPES OF METAL,"Different categories of metallic elements.",COPPER,"A reddish-brown metal used in electrical wiring.",ALUMINUM,"A lightweight silvery metal used in cans.",TITANIUM,"A strong corrosion-resistant metal for aircraft.",PLATINUM,"A rare precious metal used in jewelry.",3,Science
187,GENETICS TERMS,"Vocabulary related to DNA and heredity.",GENE,"The basic unit of heredity in living things.",CHROMOSOME,"The structure that carries genes in cells.",MUTATION,"A change in the DNA sequence of a cell.",GENOME,"The complete set of genetic material in a cell.",5,Science
188,TYPES OF SAILS,"Different shapes used on wind-powered boats.",SQUARE,"A rectangular sail hung from a horizontal yard.",LATTEEN,"A triangular sail common in the Mediterranean.",SPINNAKER,"A large balloon-like sail for downwind sailing.",STAYSAIL,"A sail set on a stay between two masts.",5,Lifestyle
189,FAMOUS EXPLORERS OF SPACE,"People who traveled beyond Earth.",ARMSTRONG,"The first person to walk on the moon.",GAGARIN,"The first human to orbit the Earth.",GLENN,"The first American to orbit the Earth.",SHEPARD,"The first American to travel into space.",3,History
190,PARTS OF THE BRAIN,"Biological regions with specific functions.",CEREBRUM,"The largest part responsible for thinking.",CEREBELLUM,"Controls balance and coordination of movement.",STEM,"Connects the brain to the spinal cord.",LOBE,"A major subdivision of the cerebral cortex.",5,Science
191,ECOLOGICAL TERMS,"Vocabulary related to the environment.",HABITAT,"The natural home or environment of an organism.",BIOME,"A large community of plants and animals.",ECOSYSTEM,"A system of interacting organisms and their home.",NICHE,"The specific role an organism has in its habitat.",3,Nature
192,TYPES OF GARDENS,"Different styles of cultivated land.",ENGLISH,"A style focusing on natural-looking landscapes.",ZEN,"A Japanese rock garden used for meditation.",KITCHEN,"A garden used for growing herbs and vegetables.",BOTANICAL,"A collection of living plants for study.",3,Lifestyle
193,STOCK MARKET TERMS,"Vocabulary related to trading shares.",DIVIDEND,"A portion of company profits paid to holders.",PORTFOLIO,"A collection of financial investments held.",BULL MARKET,"A period when stock prices are rising.",BEAR MARKET,"A period when stock prices are falling.",3,Economics
194,TYPES OF CLOUDS,"Distinct visible masses of water vapor.",STRATUS,"Flat grey clouds that cover the whole sky.",ALTUS,"Mid-level clouds that can be white or grey.",CIRRO,"High thin clouds that often look wispy.",STRATO,"Low lumpy clouds that often bring drizzle.",3,Nature
195,FAMOUS PHILOSOPHERS,"Thinkers who influenced human understanding.",SOCRATES,"The Athenian founder of Western philosophy.",PLATO,"A student of Socrates and founder of the Academy.",ARISTOTLE,"A philosopher who tutored Alexander the Great.",KANT,"A major figure in modern Western philosophy.",5,History
196,BOXING TERMS,"Vocabulary used in the sport of boxing.",UPPERCUT,"A punch thrown in an upward motion.",JAB,"A quick straight punch used for testing.",HOOK,"A punch delivered with a bent arm in a curve.",KNOCKOUT,"When a fighter is unable to continue the match.",1,Sports
197,ANCIENT ROMAN BUILDINGS,"Structures from the Roman architectural era.",PANTHEON,"A temple with a massive concrete dome.",FORUM,"The central public square in a Roman city.",AQUEDUCT,"A structure used to transport water to cities.",CIRCUS,"A large arena used for chariot racing.",3,History
198,TYPES OF ENERGY,"Broad categories of physical power.",KINETIC,"The energy possessed by an object in motion.",POTENTIAL,"Stored energy waiting to be released.",THERMAL,"Energy related to the heat of an object.",CHEMICAL,"Energy stored in the bonds of molecules.",3,Science
199,FAMOUS OPERAS,"Well-known musical theatrical productions.",CARMEN,"A story of love and tragedy in Spain.",AIDA,"A tragic love story set in ancient Egypt.",TOSCA,"A dynamic opera set in 19th-century Rome.",FALSTAFF,"A comedic opera by Giuseppe Verdi.",5,Music
200,ASTRONOMY PHENOMENA,"Events observed in the night sky.",ECLIPSE,"When one celestial body blocks light from another.",AURORA,"Bright lights in the sky near the poles.",SUPERNOVA,"A massive explosion of a dying star.",TRANSIT,"When a planet passes in front of its star.",5,Astronomy
201,MYTHOLOGICAL PLACES,"Legendary locations from world myths.",OLYMPUS,"The mountain home of the Greek gods.",VALHALLA,"The majestic hall for heroes in Norse myth.",ATLANTIS,"The legendary sunken city first told by Plato.",ELYSIUM,"The peaceful paradise for heroes in Greek myth.",3,Mythology
202,TYPES OF WINE,"Broad categories of fermented grape drinks.",MERLOT,"A soft and popular red wine variety.",CHARDONNAY,"A widely planted white wine grape.",RIESLING,"A white grape variety known for its acidity.",PROSECCO,"An Italian sparkling white wine.",3,Food
203,FAMOUS ARCHAEOLOGICAL SITES,"Locations of historical discovery.",KNOSSOS,"The Minoan palace complex on the island of Crete.",TROY,"The setting of the legendary Trojan War.",POMPEII,"The Roman city buried by volcanic ash.", Petra,"An ancient city carved into red cliffs in Jordan.",3,History
204,BIRD ANATOMY,"Biological components of avian species.",BEAK,"The hard pointed mouth of a bird.",WING,"The appendage used for flying or gliding.",CLAW,"The sharp horny nail on the foot of a bird.",TALON,"The large sharp claw of a bird of prey.",5,Animals
205,TYPES OF GLASS,"Different materials and manufacturing styles.",STAINED,"Colored glass used in decorative windows.",TEMPERED,"Glass treated with heat for increased strength.",CRYSTAL,"High-quality glass containing lead oxide.",FROSTED,"Glass treated to have a translucent finish.",5,Art
206,FAMOUS MUSICALS,"Iconic stage productions with songs.",HAMILTON,"A rap-influenced musical about US history.",WICKED,"A story about the witches of Oz before Dorothy.",CATSBALLET,"A long-running musical featuring dancing cats.",CHICAGO,"A jazz-age musical about fame and crime.",3,Music
207,PHYSICS TERMS,"Vocabulary related to matter and energy.",GRAVITY,"The force that pulls objects toward each other.",FRICTION,"The force that resists the motion of objects.",INERTIA,"The tendency of an object to remain at rest.",QUANTUM,"The study of particles at the smallest scales.",5,Science
208,TYPES OF SHIPS,"Broad categories of large marine vessels.",CARRIER,"A massive warship that serves as an airbase.",TANKER,"A ship designed for carrying large amounts of liquid.",FRIGATE,"A versatile warship smaller than a destroyer.",YACHT,"A luxurious vessel used for private cruising.",3,Lifestyle
209,FAMOUS LIBRARIES,"Well-known institutions for books and study.",ALEXANDRIA,"The most famous library of the ancient world.",VATICAN,"The private library of the Catholic Church.",BRITISH,"The national library of the United Kingdom.",CONGRESS,"The largest library in the world located in DC.",5,Literature
210,PARTS OF A ROCKET,"Structural components of a space vehicle.",STAGE,"A segment of a rocket that is discarded in flight.",ENGINE,"The machine that provides thrust for the launch.",NOZZLE,"The opening that directs the exhaust gases.",CAPSULE,"The part of the rocket that carries the crew.",5,Astronomy
`;
